project:
  type: website
  execute-dir: project
  output-dir: docs
  resources:
    - "CNAME"

website:
  title: "Yanjik&Aleni JG*inA"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
    right:
      - text: "Login"
        href: https://bestewochenende.github.io/bestewochenende/login/
  page-footer:
    right: "Built in Quarto."
    left: "© 2025, Patrick Altmeyer & Daniëlle Kotter"

format:
  html:
    theme:
      - brand
    toc: true
